Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using BarkBuddyApp.Models;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace BarkBuddyApp.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private readonly ApplicationDbContext _context;

        public ProductsController()
        {
            _context = new ApplicationDbContext(); // Initialize your DbContext
        }
       

        // GET: Products
      
        [HttpGet]
        public async Task<ActionResult> Index(string searchString)
        {
            ViewBag.ShowSearchForm = true;
      
            if (string.IsNullOrEmpty(searchString))
            {
                var products = db.Products.Include(p => p.Producer);
                return View(products.ToList());
            }
            else {
                var products = db.Products.Include(p => p.Producer);


                if (!string.IsNullOrEmpty(searchString))
                {
                    // Ensure the search is being applied to the 'Name' property
                    products = products.Where(p => p.Name.Contains(searchString));
                }

                var filteredProducts = await products.ToListAsync();  // Execute query
                return View(filteredProducts);
            }
        }

      

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            Producer nov=db.Producers.Find(product.ProducerId);
            product.Producer = nov;
            string name= product.Producer.Name;
            ViewBag.Name = name;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.ProducerId = new SelectList(db.Producers, "Id", "Name");
            ViewBag.DogBreeds = new MultiSelectList(db.DogBreeds, "Id", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price,Price2,ImageUrl,ProducerId")] Product product, int[] DogBreeds)
        {
            if (ModelState.IsValid)
            {
                Producer producer = db.Producers.Find(product.ProducerId);
               
                if (producer != null)
                {
                    product.Producer = producer;
                }
                product.DogBreeds = db.DogBreeds.Where(b => DogBreeds.Contains(b.Id)).ToList();

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProducerId = new SelectList(db.Producers, "Id", "Name", product.ProducerId);
            ViewBag.DogBreeds = new MultiSelectList(db.DogBreeds, "Id", "Name");
            return View(product);
        }

        public ActionResult DeliveryInfo()
        {

            ShoppingCart shoppingCart = (ShoppingCart)Session["ShoppingCart"];

            
            var model = new OrderViewModel
            {
                Buyer = new Buyer(),
                ShoppingCartItems = shoppingCart.BuyingProducts.Select((product, index) => new ShoppingCartItem
                {
                    ProductName = product,
                    Price = shoppingCart.Prices[index],
                    Quantity = shoppingCart.Quantities[index]
                }).ToList()
            };

            return View(model); 
        }

     
        [HttpPost]
        public ActionResult DeliveryInfo(Buyer buyer)
        {
            ShoppingCart shoppingCart = (ShoppingCart)Session["ShoppingCart"];
            if (ModelState.IsValid)
            {
         
                db.Buyers.Add(buyer);
                db.SaveChanges();

                
                var orderViewModel = new OrderViewModel
                {
                    Buyer = buyer,
                    ShoppingCartItems = shoppingCart.BuyingProducts.Select((product, index) => new ShoppingCartItem
                    {
                        ProductName = product,
                        Price = shoppingCart.Prices[index],
                        Quantity = shoppingCart.Quantities[index]
                        
                    }).ToList()
                };

         
                db.Orders.Add(orderViewModel);
                db.SaveChanges();
                Session["ShoppingCart"] = null;

                

            
                return RedirectToAction("Succ");
            }

            
            return View(buyer);
        }



        public ActionResult Orders()
        {
            var orderData = db.Orders
                               .Include(o => o.Buyer)  
                               .ToList();  

            return View(orderData);
        }




        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include(p => p.DogBreeds).FirstOrDefault(p => p.Id == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProducerId = new SelectList(db.Producers, "Id", "Name", product.ProducerId);
            ViewBag.DogBreeds = new MultiSelectList(db.DogBreeds, "Id", "Name", product.DogBreeds.Select(b => b.Id).ToArray());
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price,Price2,ImageUrl,ProducerId")] Product product, int[] DogBreeds)
        {
            if (ModelState.IsValid)
            {
                var existingProduct = db.Products.Include(p => p.DogBreeds).FirstOrDefault(p => p.Id == product.Id);

                if (existingProduct != null)
                {
                    
                    existingProduct.Name = product.Name;
                    existingProduct.Description = product.Description;
                    existingProduct.Price = product.Price;
                    existingProduct.Price2 = product.Price2;
                    existingProduct.ImageUrl = product.ImageUrl;
                    existingProduct.ProducerId = product.ProducerId;

                    existingProduct.DogBreeds.Clear();
                    if (DogBreeds != null && DogBreeds.Any())
                    {
                        existingProduct.DogBreeds = db.DogBreeds.Where(b => DogBreeds.Contains(b.Id)).ToList();
                    }
                    db.Entry(existingProduct).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.ProducerId = new SelectList(db.Producers, "Id", "Name", product.ProducerId);
            ViewBag.DogBreeds = new MultiSelectList(db.DogBreeds, "Id", "Name", DogBreeds);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [Authorize(Roles ="User")]
        public ActionResult AddToCart(int? id, int quantity = 1)
        {
            Console.WriteLine("AddToCart called with Product ID: " + id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            // Retrieve or initialize shopping cart from session
            ShoppingCart cart = Session["ShoppingCart"] as ShoppingCart;
            if (cart == null)
            {
                cart = new ShoppingCart();
            }

            // Add the product to the cart
            cart.AddProduct(product.Name, product.Price, quantity);

            // Save the cart back to the session
            Session["ShoppingCart"] = cart;

            return RedirectToAction("Index");  // Redirect back to the product list or another page

        }
        [Authorize(Roles = "User")]
        public ActionResult AddToCart2(int? id, int quantity = 1)
        {

Controllers/ToysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BarkBuddyApp.Models;

namespace BarkBuddyApp.Controllers
{
    public class ToysController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Toys
        //public ActionResult Index()
        //{
        //    return View(db.Toys.ToList());
        //}

        public async Task<ActionResult> Index(string searchString)
        {
            ViewBag.ShowSearchForm2 = true;
            var toys = db.Toys.AsQueryable();
            if (string.IsNullOrEmpty(searchString))
            {
               
                return View(toys.ToList());
            }
            else
            {
    
               
                    // Ensure the search is being applied to the 'Name' property
                    toys = toys.Where(p => p.Name.Contains(searchString));
                

                var filteredProducts = await toys.ToListAsync();  // Execute query
                return View(filteredProducts);
            }
        }

        // GET: Toys/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toys toys = db.Toys.Find(id);
            if (toys == null)
            {
                return HttpNotFound();
            }
            return View(toys);
        }

        // GET: Toys/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Toys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ImageUrl,Description,Price")] Toys toys)
        {
            if (ModelState.IsValid)
            {
                db.Toys.Add(toys);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toys);
        }

        // GET: Toys/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toys toys = db.Toys.Find(id);
            if (toys == null)
            {
                return HttpNotFound();
            }
            return View(toys);
        }

        // POST: Toys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ImageUrl,Description,Price")] Toys toys)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toys).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toys);
        }

        // GET: Toys/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toys toys = db.Toys.Find(id);
            if (toys == null)
            {
                return HttpNotFound();
            }
            return View(toys);
        }

        // POST: Toys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Toys toys = db.Toys.Find(id);
            db.Toys.Remove(toys);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap JavaScript (Popper is included in Bootstrap 5) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
   

    <style>
        .form-container {
            display: flex;
            justify-content: center;
            padding-right: 100px; 
            padding-bottom: 20px;
        }

        .form-inline {
            display: flex;
            align-items: center;
        }

            .form-inline .form-control {
                margin-right: 5px; 
            }

            .form-inline .btn {
                display: flex;
                align-items: center;
            }
    </style>




</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark" style="background-color:seagreen;">
        <div class="container">
            <i style="font-size: 3rem; color:black;">&#x1F43E;</i>
          
            @Html.ActionLink("BarkBuddy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @*<li>@Html.ActionLink("Shop", "Index", "Products", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Shop
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Food", "Index", "Products", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li>@Html.ActionLink("Accessories & Toys", "Index", "Toys", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dog Grooming
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Prices for Grooming", "Index", "GroomingDogs", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li>@Html.ActionLink("Schedule Grooming", "ScheduleGrooming", "Products", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                    @if (User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("DogBreeds", "Index", "DogBreeds", new { area = "" }, new { @class = "nav-link" })</li>

                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>@Html.ActionLink("Orders", "Orders", "Products", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Grooming Reservations", "Groomings", "Products", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Producers", "Index", "Producers", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("DogBreeds", "Index", "DogBreeds", new { area = "" }, new { @class = "dropdown-item" })</li>
                            </ul>
                        </li>
                    }

                </ul>



                <div class="form-container">
                    @if (ViewBag.ShowSearchForm != null && (bool)ViewBag.ShowSearchForm)
                    {
                        <form class="form-inline my-2 my-lg-0" asp-controller="Products" asp-action="Index" method="get" style="padding-top:25px; padding-right:30px;">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a product..." aria-label="Recipient's username" aria-describedby="button-addon2">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search icon-search" style="color:white; font-size: 1.5rem;"></i></button>
                        </form>
                    }
                    @if (ViewBag.ShowSearchForm2 != null && (bool)ViewBag.ShowSearchForm2)
                    {
                        <form class="form-inline my-2 my-lg-0" asp-controller="Toys" asp-action="Index" method="get" style="padding-top:25px; padding-right:30px;">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a product..." aria-label="Recipient's username" aria-describedby="button-addon2">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search icon-search" style="color:white; font-size: 1.5rem;"></i></button>
                        </form>
                    }
                </div>




                
                @if (User.IsInRole("User"))
                {
                <a style="text-decoration: none; color: inherit;" href="/Products/ShoppingCart"><i class="bi bi-cart-plus" style="font-size:2rem; padding-right:30px;"></i></a>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
   @* @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>